#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat << 'EOF'
╭─────────────────────────────────────────────────────────────╮
│  breakmd - Split and reassemble markdown files by headings  │
╰─────────────────────────────────────────────────────────────╯

USAGE:
  breakmd.sh [MODE] [TARGET]

MODES:
  -b, --break <file.md>     Split a markdown file into sections
                            • Creates numbered files per heading
                            • Adds navigation links between sections
                            • Generates a MANIFEST.md index

  -f, --fix <directory>     Reassemble split files into one document
                            • Merges files in sequential order
                            • Removes navigation markers
                            • Outputs to {directory}_reassembled.md

EXAMPLES:
  breakmd.sh --break document.md     Split document.md
  breakmd.sh --fix document/         Reassemble document/ directory

EOF
  exit 1
}

sanitize() {
  local raw="$1"

  raw="$(echo "$raw" | tr '[:upper:]' '[:lower:]')"
  raw="$(echo "$raw" | sed 's/[ ]\+/_/g')"
  raw="$(echo "$raw" | sed 's/[^a-z0-9_]/-/g')"
  raw="$(echo "$raw" | sed 's/-\{2,\}/-/g')"
  raw="$(echo "$raw" | sed 's/^-//; s/-$//')"

  echo "$raw"
}

break_file() {
  local input="$1"

  if [ ! -f "$input" ]; then
    echo "Error: File not found: $input"
    exit 1
  fi

  local basename="$(basename "$input" .md)"
  local outdir="./${basename}"

  mkdir -p "$outdir"

  local idx=1
  local current_file=""
  local previous_file=""
  local buffer=""
  local -a all_files=()
  local -a all_headings=()

  # Read the file line by line
  while IFS='' read -r line || [[ -n "$line" ]]; do

    if [[ "$line" =~ ^\#{1,6}[[:space:]]+(.*) ]]; then
      heading="${BASH_REMATCH[1]}"
      sanitized="$(sanitize "$heading")"
      seq=$(printf "%03d" "$idx")
      idx=$((idx+1))

      # Write previous file with navigation
      if [ -n "$current_file" ]; then
        # Determine next filename
        local next_file="${seq}_${sanitized}.md"

        # Build complete content with navigation
        local content=""
        if [ -n "$previous_file" ]; then
          content="[[$(basename "$previous_file")|BREAKMD:PREV]]"$'\n'
        fi
        content+="$buffer"
        content+="[[$(basename "$next_file")|BREAKMD:NEXT]]"$'\n'

        echo -n "$content" > "$current_file"
      fi

      # Track for manifest
      all_files+=("${seq}_${sanitized}.md")
      all_headings+=("$heading")

      # Setup next iteration
      previous_file="$current_file"
      current_file="$outdir/${seq}_${sanitized}.md"
      buffer="$line"$'\n'

    else
      buffer+="$line"$'\n'
    fi

  done < "$input"

  # Write last buffer (no next link for last file)
  if [ -n "$current_file" ]; then
    local content=""
    if [ -n "$previous_file" ]; then
          content="[[$(basename "$previous_file")|BREAKMD:PREV]]"$'\n'
    fi
    content+="$buffer"
    echo -n "$content" > "$current_file"
  fi

  # Generate manifest
  local manifest="$outdir/MANIFEST.md"
  {
    echo "# MANIFEST"
    echo ""
    echo "Generated by breakmd from: $input"
    echo ""
    echo "## Files"
    echo ""
    for i in "${!all_files[@]}"; do
      echo "- [[${all_files[$i]}|${all_headings[$i]}]]"
    done
  } > "$manifest"

  echo "Split complete. Files stored in: $outdir/"
  echo "Manifest generated: $manifest"
}

fix_directory() {
  local dir="$1"

  if [ ! -d "$dir" ]; then
    echo "Error: Directory not found: $dir"
    exit 1
  fi

  local out="${dir%/}_reassembled.md"

  # Merge in order: 000_*, 001_*, 002_*, ...
  # Skip MANIFEST.md and strip navigation markers
  (
    cd "$dir"
    ls -1 | grep -v "^MANIFEST.md$" | sort | while read -r file; do
      # Filter out BREAKMD navigation markers
      grep -v "BREAKMD:" || true
      echo
    done
  ) > "$out"

  echo "Reassembled file created: $out"
}

# ----------------- MAIN -----------------

if [ $# -lt 2 ]; then
  usage
fi

mode="$1"

case "$mode" in
  -b|--break)
    break_file "$2"
    ;;
  -f|--fix)
    fix_directory "$2"
    ;;
  *)
    usage
    ;;
esac
